# yaml-language-server: $schema=https://schemas.lbrunner.net/home-assistant/configuration.schema.json

default_config:

homeassistant:
  debug: true

http:
  server_port: 8124

logger:
  default: info
  logs:
    custom_components.gwell_ipcam: debug
    custom_components.gwell_ipcam.wire: warning
