# yaml-language-server: $schema=https://schemas.lbrunner.net/home-assistant/configuration.schema.json

frontend:
config:
history:
logbook:
dhcp:
media_source:
stream:

go2rtc:
  url: http://127.0.0.1:1984

homeassistant:
  debug: true

http:
  server_port: 8124

logger:
  default: info
  logs:
    custom_components.gwell_ipcam: debug
    custom_components.gwell_ipcam.wire: debug
    homeassistant.components.stream: debug
    homeassistant.components.camera: debug
